Home page - (The Next Web Clone) - Milestones 1-6
udberg/the-next-web-clone pull request #1
Opened 2020-12-02 16:09 UTC by SamArsanios

In this project:

- We created mobile, tablet, and pc responsive designs for the site using media queries.
- created sections and used flexbox, inlines to align pages.

2020-12-02 18:49 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @udberg and @SamArsanios, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating thenextweb.com. Most requirements have been done 👌,  kindly fix the following issues.

[REQUIRED]

- [ ] On medium screens, the navbar should contain the thenextweb.com logo at the left of the header.

- [ ] The TNW logo on the top news should disappear on medium and small screens.

- [x] The hamburger menu should appear on the right top corner of small screens.

- [x] Fix the spacing on the top news left side

- [x] Remove DS_Store file from the GitHub repo and Add it inside .gitignore

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-03 12:05 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SamArsanios and @udberg  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]
- [x] The top three articles should take the whole width of the screen each one, learn the screenshots below to see how the original page differ from your clone on mobile screen and work on it accordingly

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-03 13-59-38](https://user-images.githubusercontent.com/56886064/101015273-d2403f80-356f-11eb-8060-2484eaf075f9.png)| ![Screenshot from 2020-12-03 14-00-23](https://user-images.githubusercontent.com/56886064/101015330-ea17c380-356f-11eb-8fb4-052f6a099d04.png)|

:point_right: Could you see the difference :question: :question: :question: 
- [x]  The TNW logo on the top news should disappear on medium and small screens.
- [x] Implement all changes I suggested in inline comments in your codes

# [Optional changes]
- [x] Your commit messages should be in imperative mode or present tense, _i.e_ you should have written `Fix linter errors` instead of writting `Fixed linter errors`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

___
_If anything seems to be unclear to you, comment on this Pull Request and mention me as [@descholar-ceo](https://github.com/descholar-ceo) I will receive a notification and will respond._

| [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-12-03 12:05 UTC, descholar-ceo commented on .gitignore
> +.stylelintrc.json
Remove this `.hintrc` and `.stylelintrc.json` files from gitignore :point_right: They are linting files, so you need them in your repository

2020-12-03 12:05 UTC, descholar-ceo commented on index.html
> +    </section> -->
Remove the commented codes

2020-12-03 12:05 UTC, descholar-ceo commented on index.html
> +                </div> -->
This commented code also should be removed

2020-12-03 15:53 UTC, abredi approved these changes
### Status: Approved 🙌 🎇
Hi @udberg and @SamArsanios, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏  I appreciate your hard work in replicating thenextweb.com.

Now, you can move ahead.

Please don't forget to merge to master. Good luck with the next projects!

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-03 16:34 UTC, SamArsanios commented
> ### Status: Approved 🙌 🎇
> Hi @udberg and @SamArsanios, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Congratulations 🎊 👏, you did very well on this project. 👏👏 I appreciate your hard work in replicating thenextweb.com.
> 
> Now, you can move ahead.
> 
> Please don't forget to merge to master. Good luck with the next projects!
> 
> Happy coding 👨‍💻
> [Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-03 16:35 UTC, SamArsanios commented on index.html
> +                </div> -->
Thanks a lot for the review

2020-12-03 16:38 UTC, merged